-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 11:18:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bpsjboa54x4kpuw1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bpsjboa54x4kpuw1` ;

-- -----------------------------------------------------
-- Schema bpsjboa54x4kpuw1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bpsjboa54x4kpuw1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bpsjboa54x4kpuw1` ;

-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Colors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_product` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `measures` VARCHAR(255) NULL DEFAULT NULL,
  `discount` INT(11) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `id_category` INT(11) NULL DEFAULT NULL,
  `id_color` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `Colors_id` INT(11) NOT NULL,
  `Categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Colors1_idx` (`Colors_id` ASC) VISIBLE,
  INDEX `fk_Products_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Colors1`
    FOREIGN KEY (`Colors_id`)
    REFERENCES `bpsjboa54x4kpuw1`.`Colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `bpsjboa54x4kpuw1`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_product` INT(11) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `Products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Images_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_Images_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `bpsjboa54x4kpuw1`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `admin` TINYINT(1) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`Products_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`Products_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_product` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `Products_id` INT(11) NOT NULL,
  `Users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_users_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_Products_users_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_users_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `bpsjboa54x4kpuw1`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_users_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `bpsjboa54x4kpuw1`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bpsjboa54x4kpuw1`.`SequelizeMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpsjboa54x4kpuw1`.`SequelizeMeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
